#+TITLE: main
#+AUTHOR: Vladimir Ryazansew
#+EMAIL: elf.forest@yandex.ru
#+DATE: Четверг, декабря  7 2023
#+OPTIONS: num:nil
#+SETUPFILE: ./setupfiles/header.setup

| *Author* | {{{author}}} ({{{email}}})    |
| *Date*   | {{{time(%Y-%m-%d %H:%M:%S)}}} |

* Russian doll Operating System :os:
:PROPERTIES:
:CUSTOM_ID: Russian doll
:END:

* Как использовать эти файлы

* License
#+BEGIN_QUOTE
Copyright (C) 2023-{{{time(%Y)}}} {{{author}}} ({{{email}}}) 

Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.3
or any later version published by the Free Software Foundation;
with no Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts.

Code in this document is free software: you can redistribute it
and/or modify it under the terms of the GNU General Public
License as published by the Free Software Foundation, either
version 3 of the License, or (at your option) any later version.

This code is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
#+END_QUOTE
